# docker-compose.yml

version: '3.8'

services:
# --- Backend services (express.js) ---
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: express_backend
    ports:
      - "3030:3030"
    environment:
      NODE_ENV: ${NODE_ENV}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      JWT_SECRET: ${JWT_SECRET}

    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  # --- Frontend service ---
  frontend:
    image: nginx:stable-alpine
    container_name: frontend

    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
  
  # --- Database service ---
  db:
    image: postgres:16-alpine
    container_name: postgres_db

    environment:
      POSTGRES_USER: ${postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  pgdata: